### ISSUE TITLE
Error in implementing code for Matconvnet in Gpu

### ISSUE THREAD

**Issue by preetivyas** [siavashBigdeli/DMSP#2]
I am trying to implement the code for MatConvNet Gpu version. 
MATLAB version : R2016b
MatConvNet Version : matconvnet-1.0-beta25
Cuda Version - 8.0
I am getting the following error while implementing current file in github. 
![screenshot from 2018-04-02 12-40-58](https://user-images.githubusercontent.com/31855851/38205062-2e86da78-3673-11e8-9bd0-b04986c3574f.png)

I have tried changing 
net.layers = net
to net1.layers = net 
the code runs for one iteration and then again there is some error.
![screenshot from 2018-04-02 12-43-57](https://user-images.githubusercontent.com/31855851/38205161-8dc9ce28-3673-11e8-84b5-12aa99c317f1.png)

Please help me sort this error. Thanks.

Edit  -

I guess the problem is with the pretrained file format- DAE.sigmall.mat
The net loaded from that file have a different format where we don't actually have layers,
![screenshot from 2018-04-02 19-10-48](https://user-images.githubusercontent.com/31855851/38220718-bd4876fa-36a9-11e8-8dc6-aa736371ad20.png)

When we add this line
<net.layers = net>

A reference to the same net file is created like this
![layers](https://user-images.githubusercontent.com/31855851/38220788-2bab6526-36aa-11e8-8422-79495aaea2b4.png)

Which is not the layers that we are trying to access later in code block vl_simplenn_move.
I followed the same code with a different trained model given in matconvnet website. The net format looks like this 
![screenshot from 2018-04-02 19-10-17](https://user-images.githubusercontent.com/31855851/38220834-72171726-36aa-11e8-97f1-df72c928779a.png)

Here as we can see each layer can be accessed here.
![layers open](https://user-images.githubusercontent.com/31855851/38220982-2800a354-36ab-11e8-811f-762ed6d962d7.png)

I still don't know how to use the pre-trained file in current format for the code.

**Comment by siavashBigdeli** [comment]
Can you reproduce the error using inly the CPU (setting use_gpu to 0)?
Could you make sure that your Matlab's workspace is clear during your experiments?

**Comment by preetivyas** [comment]
So the code is working for cpu version and gave me results after a small change in loadMatDenoiser. 
![changed loadmatdenoiser](https://user-images.githubusercontent.com/31855851/38260188-f31b622a-3734-11e8-9bd4-45ae8aca50bd.png)

But the same code is not working for GPU when I changed the use_gpu =1.
![error in data filter mismatch](https://user-images.githubusercontent.com/31855851/38260205-f8dce436-3734-11e8-9da4-91b43b782914.png)

**Comment by preetivyas** [comment]
I got it fixed. Its the input array format issue in gpu version. 
The network is getting converted to gpuArray but not the input that is delivered to params.denoiser.
You can add a line in your code to convert the parsing of x after getting it changed to gpuArray for gpu version.

Thanks anyway for keeping in touch.

**Comment by siavashBigdeli** [comment]
Thanks for the fix!
