### ISSUE TITLE
Kernel Blind implementation

### ISSUE THREAD

**Issue by preetivyas** [siavashBigdeli/DMSP#3]
I am trying to implement kernel blind from your paper.  I was following the Table 1 in the paper for Kernel blind. I am not sure what $x^T$ is doing in 4. equation.  Is it just multiplication or convolution? In either case the size of matrix is not satisfied. We have to get a kernel as the final vt but dimensions of term $x^T(K^{t-1}x^{t-1} -y)$ is of (width x height x 3) which we need to convert to kernel which will be (width x height). I am not really sure about the update approach.
![image](https://user-images.githubusercontent.com/31855851/38441913-52fb0c78-39b4-11e8-801d-0a6a2a48cb5a.png)
As the size of v^t must be equal to the size of the kernel. I don't know how to handle the first term in 4. to maintain the size of the kernel.

**Comment by siavashBigdeli** [comment]
K is the [Toeplitz matrix](https://en.wikipedia.org/wiki/Toeplitz_matrix) of the blur kernel k.
So Kx denotes the convolution of the image x with kernel k, and x^T (x transposed) is later convolved with the residual (Kx-y). For both cases I used Matlab's convn function with 'valid' as parameter.

**Comment by tizwe** [comment]
But when we suppose that width=height, then shape(x^T)=shape(y)=shape(Kx-y).
Hence, if we convolve x^T with (Kx-y) , with 'valid' the resulting shape is (1,1) since they have the same shape. 
Also, what is the default shape of the kernel here ? Is the information of the size of true kernel given or do we just guess it in the implementation ?

**Comment by siavashBigdeli** [comment]
> But when we suppose that width=height, then shape(x^T)=shape(y)=shape(Kx-y).
> Hence, if we convolve x^T with (Kx-y) , with 'valid' the resulting shape is (1,1) since they have the same shape.
> Also, what is the default shape of the kernel here ? Is the information of the size of true kernel given or do we just guess it in the implementation ?

Sorry for the late reply Tizian. x and y do not have the same shape and K is not a square matrix. We (almost always) reconstruct x with width_x = width_y + 2*(width_mernel//2).
This ensures that the convolution you mentioned results into the same size as the kernel's.
Kernel is assumed to be a single channel array, but the horizontal and vertical dimensions are not limited.
